<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateRateEURSTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('rate_e_u_r_s', function (Blueprint $table) {
            $table->id();
            $table->text('EURAED')->nullable();
            $table->text('EURAFN')->nullable();
            $table->text('EURALL')->nullable();
            $table->text('EURAMD')->nullable();
            $table->text('EURANG')->nullable();
            $table->text('EURAOA')->nullable();
            $table->text('EURARS')->nullable();
            $table->text('EURAUD')->nullable();
            $table->text('EURAWG')->nullable();
            $table->text('EURAZN')->nullable();
            $table->text('EURBAM')->nullable();
            $table->text('EURBBD')->nullable();
            $table->text('EURBDT')->nullable();
            $table->text('EURBGN')->nullable();
            $table->text('EURBHD')->nullable();
            $table->text('EURBIF')->nullable();
            $table->text('EURBMD')->nullable();
            $table->text('EURBND')->nullable();
            $table->text('EURBOB')->nullable();
            $table->text('EURBRL')->nullable();
            $table->text('EURBSD')->nullable();
            $table->text('EURBTC')->nullable(); 
            $table->text('EURBTN')->nullable();
            $table->text('EURBWP')->nullable();
            $table->text('EURBYN')->nullable();
            $table->text('EURBYR')->nullable();
            $table->text('EURBZD')->nullable();
            $table->text('EURCAD')->nullable();
            $table->text('EURCDF')->nullable();
            $table->text('EURCHF')->nullable();
            $table->text('EURCLF')->nullable();
            $table->text('EURCLP')->nullable();
            $table->text('EURCNY')->nullable();
            $table->text('EURCOP')->nullable();
            $table->text('EURCRC')->nullable();
            $table->text('EURCUC')->nullable();
            $table->text('EURCUP')->nullable();
            $table->text('EURCVE')->nullable();
            $table->text('EURCZK')->nullable();
            $table->text('EURDJF')->nullable();
            $table->text('EURDKK')->nullable();
            $table->text('EURDOP')->nullable();
            $table->text('EURDZD')->nullable();
            $table->text('EUREGP')->nullable();
            $table->text('EURERN')->nullable();
            $table->text('EURETB')->nullable();
            $table->text('EUREUR')->nullable();
            $table->text('EURFJD')->nullable();
            $table->text('EURFKP')->nullable();
            $table->text('EURGBP')->nullable();
            $table->text('EURGEL')->nullable();
            $table->text('EURGGP')->nullable();
            $table->text('EURGHS')->nullable();
            $table->text('EURGIP')->nullable();
            $table->text('EURGMD')->nullable();
            $table->text('EURGNF')->nullable();
            $table->text('EURGTQ')->nullable();
            $table->text('EURGYD')->nullable();
            $table->text('EURHKD')->nullable();
            $table->text('EURHNL')->nullable();
            $table->text('EURHRK')->nullable();
            $table->text('EURHTG')->nullable();
            $table->text('EURHUF')->nullable();
            $table->text('EURIDR')->nullable();
            $table->text('EURILS')->nullable();
            $table->text('EURIMP')->nullable();
            $table->text('EURINR')->nullable();
            $table->text('EURIQD')->nullable();
            $table->text('EURIRR')->nullable();
            $table->text('EURISK')->nullable();
            $table->text('EURJEP')->nullable();
            $table->text('EURJMD')->nullable();
            $table->text('EURJOD')->nullable();
            $table->text('EURJPY')->nullable();
            $table->text('EURKES')->nullable();
            $table->text('EURKGS')->nullable();
            $table->text('EURKHR')->nullable();
            $table->text('EURKMF')->nullable();
            $table->text('EURKPW')->nullable();
            $table->text('EURKRW')->nullable();
            $table->text('EURKWD')->nullable();
            $table->text('EURKYD')->nullable();
            $table->text('EURKZT')->nullable();
            $table->text('EURLAK')->nullable();
            $table->text('EURLBP')->nullable();
            $table->text('EURLKR')->nullable();
            $table->text('EURLRD')->nullable();
            $table->text('EURLSL')->nullable();
            $table->text('EURLTL')->nullable();
            $table->text('EURLVL')->nullable();
            $table->text('EURLYD')->nullable();
            $table->text('EURMAD')->nullable();
            $table->text('EURMDL')->nullable();
            $table->text('EURMGA')->nullable();
            $table->text('EURMKD')->nullable();
            $table->text('EURMMK')->nullable();
            $table->text('EURMNT')->nullable();
            $table->text('EURMOP')->nullable();
            $table->text('EURMRO')->nullable();
            $table->text('EURMUR')->nullable();
            $table->text('EURMVR')->nullable();
            $table->text('EURMWK')->nullable();
            $table->text('EURMXN')->nullable();
            $table->text('EURMYR')->nullable();
            $table->text('EURMZN')->nullable();
            $table->text('EURNAD')->nullable();
            $table->text('EURNGN')->nullable();
            $table->text('EURNIO')->nullable();
            $table->text('EURNOK')->nullable();
            $table->text('EURNPR')->nullable();
            $table->text('EURNZD')->nullable();
            $table->text('EUROMR')->nullable();
            $table->text('EURPAB')->nullable();
            $table->text('EURPEN')->nullable();
            $table->text('EURPGK')->nullable();
            $table->text('EURPHP')->nullable();
            $table->text('EURPKR')->nullable();
            $table->text('EURPLN')->nullable();
            $table->text('EURPYG')->nullable();
            $table->text('EURQAR')->nullable();
            $table->text('EURRON')->nullable();
            $table->text('EURRSD')->nullable();
            $table->text('EURRUB')->nullable();
            $table->text('EURRWF')->nullable();
            $table->text('EURSAR')->nullable();
            $table->text('EURSBD')->nullable();
            $table->text('EURSCR')->nullable();
            $table->text('EURSDG')->nullable();
            $table->text('EURSEK')->nullable();
            $table->text('EURSGD')->nullable();
            $table->text('EURSHP')->nullable();
            $table->text('EURSLL')->nullable();
            $table->text('EURSOS')->nullable();
            $table->text('EURSRD')->nullable();
            $table->text('EURSTD')->nullable();
            $table->text('EURSVC')->nullable();
            $table->text('EURSYP')->nullable();
            $table->text('EURSZL')->nullable();
            $table->text('EURTHB')->nullable();
            $table->text('EURTJS')->nullable();
            $table->text('EURTMT')->nullable();
            $table->text('EURTND')->nullable();
            $table->text('EURTOP')->nullable();
            $table->text('EURTRY')->nullable();
            $table->text('EURTTD')->nullable();
            $table->text('EURTWD')->nullable();
            $table->text('EURTZS')->nullable();
            $table->text('EURUAH')->nullable();
            $table->text('EURUGX')->nullable();
            $table->text('EURUSD')->nullable();
            $table->text('EURUYU')->nullable();
            $table->text('EURUZS')->nullable();
            $table->text('EURVEF')->nullable();
            $table->text('EURVND')->nullable();
            $table->text('EURVUV')->nullable();
            $table->text('EURWST')->nullable();
            $table->text('EURXAF')->nullable();
            $table->text('EURXAG')->nullable();
            $table->text('EURXAU')->nullable();
            $table->text('EURXCD')->nullable();
            $table->text('EURXDR')->nullable();
            $table->text('EURXOF')->nullable();
            $table->text('EURXPF')->nullable();
            $table->text('EURYER')->nullable();
            $table->text('EURZAR')->nullable();
            $table->text('EURZMK')->nullable();
            $table->text('EURZMW')->nullable();
            $table->text('EURZWL')->nullable();
            $table->timestamps();
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('rate_e_u_r_s');
    }
}
